spring.application.name=first

spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.password=*Gorakhpur1
spring.datasource.username=root
pring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

logging.level.root=warn
